version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - rabbitMQ
  rabbitMQ:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
