version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitMQ
  rabbitMQ:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
